MAPCON: bugfix: Fixed bug where the useEffect of login was causing a 'TypeError: destroy is not a function' because of the way it was written as.
Tracker:
feat: News crawling and saving is working + primitive report generation for later logging on the website.